# Generated by Django 5.1.3 on 2024-12-05 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(default=1, related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
